services:
  idris2-lsp:
    build: 
      context: ./idris2-lsp
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    ports:
      - "3030:3030"
    volumes:
      - /home/zak/idris2-lsp:/workspace
    
  emacs-lsp:
    build: 
      context: ./emacs-lsp
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    ports:
      - "8080:8080"
    volumes:
      - /home/zak/idris2-lsp:/workspace
    depends_on:
      - idris2-lsp
